owner: huytz
git-repo: helm-kubernetes-services
package-path: .cr-release-packages
index-path: .cr-index/index.yaml
pages-branch: gh-pages
pages-index-path: index.yaml
release-name-template: "{{ .Name }}-{{ .Version }}"
skip-existing: true
