name: Release Charts

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Install chart-releaser
        uses: helm/chart-releaser-action@v1.5.0

      - name: Package charts
        run: |
          for chart in charts/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Packaging chart: $chart"
              cr package "$chart"
            fi
          done

      - name: Upload charts
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cr upload --token ${{ secrets.GITHUB_TOKEN }}

      - name: Create index
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cr index --token ${{ secrets.GITHUB_TOKEN }} --push
